### PR TITLE
Replace 32 bit sizes by size_t

### PR DESCRIPTION
**Pull request by krocard**
Correct size_t/uint32_t miss alignment between header and source.

### CODE REVIEW

**Comment by krocard** [comment]
This patch was a divergence between the android and github plugin.

**Comment by krocard** [comment]
@dawagner @oznog Should be merge this ?

**Comment by krocard** [comment]
I just forced push the my other pull request on this one :(
Restoring it...

**Comment by OznOg** [comment]
:+1:

**Comment by dawagner** [comment]
:shipit:

**Pull request merged**
